apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-app1
  namespace: app1
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-app2
  namespace: app2
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx